### ISSUE TITLE
Package Installation Issue

### ISSUE THREAD

**Issue by Jako** [Bruno17/siblingnav#15]
It seems that you have left a MIGX resolver in the package. It asks for 'Where to place the menu for this Extra' during install.

**Comment by Bruno17** [comment]
Thanks for the pointer.
It was packaged with migxElementsManager, which adds that resolver automatically.
I think, i should add an option to migxElementsManager to make that resolver optional.

**Comment by Bruno17** [comment]
should be fixed at 1.2.2
see https://github.com/Bruno17/migxElementsManager/commit/0b31697dcc38dde7267d28e1a3cdede505caf5d2

**Comment by Bruno17** [comment]
its now packaged with GPM
