### ISSUE TITLE
Not compatible with PHP8

### ISSUE THREAD

**Issue by sebastian-marinescu** [Bruno17/siblingnav#22]
Be aware, this extra isn't working properly under PHP8. 

To get rid of the 500 error, you'll have to fix this: https://github.com/Bruno17/siblingnav/issues/21

But then it still doesn't work properly (for me): 
- No prev button ever shows
- Next button is stuck between 2 resources

**Comment by aroy314** [comment]
@Bruno17 any plans about extending compatibility to PHP8 ?

**Comment by DavPah** [comment]
Found a super easy quick fix for the PHP 8 issue. [v](https://github.com/Bruno17/siblingnav/issues/21)

**Comment by mediengaarage** [comment]
I have the same problem. 
@Bruno17 when will the update be available?

**Comment by Lefthandmedia** [comment]
same here
